# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-02 10:38
from __future__ import unicode_literals

import data_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_app', '0002_auto_20151201_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=30)),
                ('typeOfFile', models.CharField(max_length=30)),
                ('docfile', models.FileField(upload_to=data_app.models.generate_path)),
                ('docid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
